### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by CheccoFire** [nishi7409/ClanLabs-OpenSourced#3]
Where is the tutorial? I dont find it.

**Comment by nishi7409** [comment]
Didn't find the time to do so for the main source code.  I've provided a tutorial for the aegis core source code (just scroll down the main README.md file)

Link - https://github.com/nishi7409/ClanLabs-OpenSourced/blob/master/README.md

**Comment by CheccoFire** [comment]
Thanks nishi, you are the best.
