### ISSUE TITLE
Login Cookies

### ISSUE THREAD

**Issue by drichii** [nishi7409/ClanLabs-OpenSourced#4]
Hey. So you're saying with the current ROBLOX accounts that you cannot log out of ROBLOX in order to prevent the cookie to be reset. However, what about old accounts as I heard something that they have legacy cookies or am I wrong about that. Or is there anyway to circumvent that problem with the current ROBLOX accounts.

**Comment by nishi7409** [comment]
You're not wrong.  The tutorial was meant for users who didn't have any old accounts on hand--personally, I have over eight; however, once again, I just wanted to make it really simplistic for everyone viewing the repository.
