### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by crabbynick4** [nishi7409/ClanLabs-OpenSourced#7]
"There are other clients that can do the same things as Clan Labs for absolutely free, but you can't see their source code--which sucks." -nishi7409 Can you name any of these other clients that won't show source code but will give you the service for free by chance?

**Comment by nishi7409** [comment]
I remember Terabyte Services being a thing, but don't quote me on that.  I don't know now, but I'm most definitely sure, there are some alternatives.
