### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by CheccoFire** [nishi7409/ClanLabs-OpenSourced#8]
Await error 
![Screenshot_20190623-185303_Chrome](https://user-images.githubusercontent.com/30508161/59979434-455a2e00-95e8-11e9-91a8-63662091d903.jpg)

**Comment by nishi7409** [comment]
Stick with using the source code already provided (aegis core & british army) -- i haven't touched the files you're working on at all that much.  This project is done.  I may work on a dashboard/website application, but that's later.
