### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by crabbynick4** [nishi7409/ClanLabs-OpenSourced#9]
Sorry, but I noticed you are here, can you host the bot on heroku by chance?

**Comment by nishi7409** [comment]
https://github.com/nishi7409/ClanLabs-OpenSourced/blob/master/idea/british_army_code.js - no

https://github.com/nishi7409/ClanLabs-OpenSourced/blob/master/idea/aegis_core_code.js - yes

the other stuff, yes
